baseURL: https://www.rahmatawe.com/
languageCode: en-us
theme: toha

############ TOHA CONFIG ###########
languages:
  en:
    languageName: English
    weight: 1

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

params:
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true
