hugover = "0.69.0"

[[serve]]
key = "default"
config = "config.toml"

[[build]]
key = "default"
config = "config.toml"

[[collections]]
key = "posts"
title = "Posts"
folder = "content/blog/"
extension = "md"
dataformat = "yaml"
itemtitle = "Post"

  [[collections.fields]]
  key = "title"
  title = "Title"
  type = "string"
  required = false
  pattern = ""
  multiLine = false
  default = ""
  tip = ""

  [[collections.fields]]
  key = "mainContent"
  title = "Content"
  type = "markdown"
  multiLine = true
  default = ""
  tip = ""

  [[collections.fields]]
  key = "date"
  title = "Pub Date"
  type = "date"
  default = "now"
  required = true
  tip = ""

  [[collections.fields]]
  key = "draft"
  title = "Draft"
  type = "boolean"
  default = false
  tip = ""

  [[collections.fields]]
  key = "bundle-manager"
  title = "Images"
  type = "bundle-manager"
  path = "imgs"
  extensions = [
    "png",
    "jpg",
    "gif"
  ]

    [[collections.fields.fields]]
    key = "title"
    title = "Title"
    type = "string"
    required = false
    pattern = ""
    multiLine = false
    default = ""
    tip = ""

    [[collections.fields.fields]]
    key = "description"
    title = "Description"
    type = "string"
    multiLine = true
    required = false
    pattern = ""
    default = ""
    tip = ""

    [[collections.fields.fields]]
    key = "bundle-image-thumbnail"
    type = "bundle-image-thumbnail"
    src = ""

  [[collections.fields]]
  key = "categories"
  type = "chips"
  title = "Categories"
  default = []

  [[collections.fields]]
  key = "description"
  type = "string"
  title = "Description"
  required = false
  pattern = ""
  multiLine = false
  default = ""
  tip = ""

  [[collections.fields]]
  key = "series"
  type = "chips"
  title = "series"
  default = []

  [[collections.fields]]
  key = "tags"
  type = "chips"
  title = "tags"
  default = []

[[singles]]
key = "mainConfig"
title = "Main Config"
file = "config.toml"
dataformat = "toml"

  [[singles.fields]]
  key = "title"
  title = "Site Title"
  type = "string"
  tip = "Your page title."
  required = false
  pattern = ""
  multiLine = false
  default = ""

  [[singles.fields]]
  key = "baseURL"
  title = "Base URL"
  type = "string"
  tip = "Your site URL."
  required = false
  pattern = ""
  multiLine = false
  default = ""

  [[singles.fields]]
  key = "theme"
  title = "Theme"
  type = "readonly"
  tip = "The current theme."
  required = false
  value = ""
  default = ""
  multiLine = false

  [[singles.fields]]
  key = "languageCode"
  title = "Language Code"
  type = "readonly"
  required = false
  value = ""
  default = ""
  multiLine = false
  tip = ""

  [[singles.fields]]
  key = "googleAnalytics"
  title = "Google Analytics"
  type = "string"
  tip = "Provide a Google Analitics Tracking Code to enable analytics."
  required = false
  pattern = ""
  multiLine = false
  default = ""

  [[singles.fields]]
  key = "enableRobotsTXT"
  title = "Enable Robots"
  type = "boolean"
  default = true
  tip = "If you want your page to be indexed, keep this enabled."